Repository PETWIF/Front-End, pull requests merged in 2024-09, with the labels that each got.

#109 #105 [FEAT] 댓글 및 앨범 좋아요 연결
  .yarnrc.yml
  src/apis/album.js
  src/apis/comment.js
  src/components/AlbumDetail/CommentSection.jsx
  src/components/Feed/CommentSection.jsx
  src/components/Feed/FeedItem.jsx
  src/hooks/useLike.jsx
  src/pages/AlbumDetailPage/AlbumDetailPage.jsx
  yarn.lock
Labels: ↔️ API

#112 [MERGE] 배포 브랜치 반영
  .yarnrc.yml
  src/App.jsx
  src/apis/addInfo.js
  src/apis/album.js
  src/apis/block.js
  src/apis/comment.js
  src/apis/deleteAccount.js
  src/apis/getMyProfile.js
  src/apis/login.js
  src/apis/nickname.js
  src/apis/report.js
  src/components/AlbumDetail/CommentSection.jsx
  src/components/AlbumMaking/MainArea.jsx
  src/components/AlbumMaking/MakingModal.jsx
  src/components/AlbumMaking/MakingModal.style.jsx
  src/components/AlbumMaking/Side.jsx
  src/components/Feed/CommentSection.jsx
  src/components/Feed/Feed.style.jsx
  src/components/Feed/FeedItem.jsx
  src/components/Header/Header.jsx
  src/components/LoginComponents/LoginHeader.jsx
  src/components/Profile/Profile.jsx
  src/components/RandomFriend/RandomFriend.jsx
  src/components/ReportComponents/ReportModal.jsx
  src/components/ReportComponents/ReportModal.style.jsx
  src/components/Sidebar/Sidebar.jsx
  src/hooks/useAuth.jsx
  src/hooks/useLike.jsx
  src/hooks/useReportModal.jsx
  src/main.jsx
  src/pages/AddInfoPage/AddInfoPage.jsx
  src/pages/AgreePage/AgreePage.jsx
  src/pages/AlbumDetailPage/AlbumDetailPage.jsx
  src/pages/AlbumMakingPage/AlbumMakingPage.jsx
  src/pages/AlbumPage/AlbumItem/AlbumItem.jsx
  src/pages/AlbumPage/AlbumPage/AlbumPage.jsx
  src/pages/FriendPage/FriendList/FriendList.jsx
  src/pages/FriendPage/FriendReceivedList/FriendReceivedList.jsx
  src/pages/FriendPage/FriendSentList/FriendSentList.jsx
  src/pages/LoginPage/LoginPage.jsx
  src/pages/LoginPage/LoginPage.style.jsx
  src/pages/LoginPage/handleSocialLogin.jsx
  src/pages/MainPage/MainPage.jsx
  src/pages/MainPage/MainPage.style.jsx
  src/pages/PwdChangePage/PwdChangePage.jsx
  src/pages/PwdSearchPage/PwdSearchPage.jsx
  src/pages/RegisteredPage/RegisteredPage.jsx
  src/pages/RegisteredPage/RegisteredPage.style.jsx
  src/pages/SetNicknamePage/SetNicknamePage.jsx
  src/pages/SetNicknamePage/SetNicknamePage.style.jsx
  src/pages/SettingPage/BlockListPage/BlockListPage.jsx
  src/pages/SettingPage/DeleteAccountPage/DeleteAccountPage.jsx
  src/pages/SignUpPage/SignUpPage.jsx
  src/route.jsx
  yarn.lock
Labels: 🌏 Deploy

#116 [MODIFY] 인증번호 로직, 회원가입 완료 페이지, 로그아웃 수정
  src/apis/certificationCode.js
  src/apis/getMyProfile.js
  src/apis/nickname.js
  src/hooks/useAuth.jsx
  src/pages/AddInfoPage/AddInfoPage.jsx
  src/pages/AgreePage/AgreePage.jsx
  src/pages/LoginPage/handleSocialLogin.jsx
  src/pages/PwdSearchPage/PwdSearchPage.jsx
  src/pages/RegisteredPage/RegisteredPage.jsx
  src/pages/SetNicknamePage/SetNicknamePage.jsx
  src/pages/SettingPage/DeleteAccountPage/DeleteAccountPage.jsx
  src/pages/SignUpPage/SignUpPage.jsx
Labels: 🔧 Fix

#126 [FEAT] 프로필 수정 api 연결
  src/hooks/useAuth.jsx
  src/pages/AddInfoPage/AddInfoPage.jsx
  src/pages/UserProfilePage/UserProfilePage.jsx
  src/pages/UserProfilePage/UserProfilePage.style.jsx
Labels: ✨ Feature, ↔️ API

#128 #127 [FIX] 홈 피드에서 앨범 상세로 넘어가는 링크 경로 수정
  src/components/Feed/FeedItem.jsx
Labels: 🔧 Fix

#129 [MERGE] 홈 피드에서 앨범 상세로 이동하는 경로 수정
  src/apis/block.js
  src/components/Feed/FeedItem.jsx
  src/hooks/useAuth.jsx
  src/pages/AddInfoPage/AddInfoPage.jsx
  src/pages/LoginPage/handleSocialLogin.jsx
  src/pages/SettingPage/BlockListPage/BlockListPage.jsx
  src/pages/SettingPage/BlockListPage/BlockListPage.style.jsx
  src/pages/SignUpPage/SignUpPage.jsx
  src/pages/UserProfilePage/UserProfilePage.jsx
  src/pages/UserProfilePage/UserProfilePage.style.jsx
  yarn.lock
Labels: 🌏 Deploy

#131 #130 [FEAT] 홈 피드에서 프로필 링크 클릭 시 해당 유저의 앨범 페이지로 이동
  src/components/Feed/FeedItem.jsx
  src/pages/AlbumPage/AlbumPage/AlbumPage.jsx
  yarn.lock
Labels: ✨ Feature

#134 [FEAT] 채팅 신고 기능 임시 구현 및 Profile.jsx 리팩터링
  src/components/Chatting/Chatting.jsx
  src/components/Chatting/Chatting.style.jsx
  src/components/Profile/Profile.jsx
  src/pages/LoginPage/LoginPage.jsx
  src/pages/LoginPage/LoginPage.style.jsx
Labels: 🛠️ Refactor, ✨ Feature

#138 #137 [FIX] Profile 훅 호출 순서 보장
  src/components/Profile/Profile.jsx
Labels: 🔧 Fix

#139 [MERGE] 배포 브랜치로 머지
  src/apis/block.js
  src/components/Chatting/Chatting.jsx
  src/components/Chatting/Chatting.style.jsx
  src/components/Profile/Profile.jsx
  src/pages/AlbumPage/AlbumPage/AlbumPage.jsx
  src/pages/LoginPage/LoginPage.jsx
  src/pages/LoginPage/LoginPage.style.jsx
Labels: 🌏 Deploy

#141 #140 [FIX] 탐색 피드 Link에 변경된 라우트 적용
  src/dummy/data/album.js
  src/pages/ExplorePage/ExplorePage.jsx
Labels: 🔧 Fix

#142 [MERGE] 탐색 피드 클릭 시 해당 유저의 앨범 페이지로 이동
  src/dummy/data/album.js
  src/pages/ExplorePage/ExplorePage.jsx
Labels: 🌏 Deploy

#149 Feat/#5 album making
  src/apis/album.js
  src/components/AlbumMaking/MainArea.jsx
  src/components/AlbumMaking/MakingModal.jsx
  src/components/AlbumMaking/Side.jsx
  src/components/Chatting/Chatting.jsx
  src/pages/AlbumMakingPage/AlbumMakingPage.jsx
Labels: ↔️ API

#157 #145[FEAT] 채팅 API 연결
  src/apis/chat.js
  src/assets/icons/icon.svg
  src/components/AlbumDetail/AlbumDetail.jsx
  src/components/Chatting/Chatting.jsx
  src/components/Chatting/Chatting.style.jsx
  src/pages/AlbumDetailPage/AlbumDetailPage.jsx
Labels: ↔️ API
