Repository PETWIF/Front-End, pull requests merged in 2024-08, with the labels that each got.

#4 #3 [FEAT] 공통 컴포넌트 개발
  package.json
  src/App.jsx
  src/assets/icons/icon.svg
  src/components/Button/Button.jsx
  src/components/Button/Button.style.jsx
  src/components/Button/index.js
  src/components/Common/index.js
  src/components/Header/Header.jsx
  src/components/Header/Header.style.jsx
  src/components/Header/index.js
  src/components/Icon/Icon.jsx
  src/components/Icon/index.js
  src/components/Modal/Modal.jsx
  src/components/Modal/Modal.style.jsx
  src/components/Modal/index.js
  src/components/Profile/Profile.jsx
  src/components/Profile/Profile.style.jsx
  src/components/Profile/index.js
  src/components/RandomFriend/RandomFriend.jsx
  src/components/RandomFriend/RandomFriend.style.jsx
  src/components/RandomFriend/index.js
  src/components/Sidebar/Sidebar.jsx
  src/components/Sidebar/Sidebar.style.jsx
  src/components/Sidebar/index.js
  src/constants/index.js
  src/constants/menu.js
  src/dummy/data/friend.js
  src/dummy/data/index.js
  src/dummy/images/index.js
  src/dummy/images/profile.jpeg
  src/dummy/index.js
  src/hooks/useModal.jsx
  src/index.css
  src/main.jsx
  src/pages/AlbumDetailPage/AlbumDetailPage.jsx
  src/pages/AlbumDetailPage/index.js
  src/pages/AlbumPage/AlbumPage.jsx
  src/pages/AlbumPage/index.js
  src/pages/AlbumPostPage/AlbumPostPage.jsx
  src/pages/AlbumPostPage/index.js
  src/pages/BookmarkPage/BookmarkPage.jsx
  src/pages/BookmarkPage/index.js
  src/pages/ChattingPage/ChattingPage.jsx
  src/pages/ChattingPage/index.js
  src/pages/ExplorePage/ExplorePage.jsx
  src/pages/ExplorePage/index.js
  src/pages/FriendPage/FriendPage.jsx
  src/pages/FriendPage/index.js
  src/pages/MainPage/MainPage.jsx
  src/pages/MainPage/index.js
  src/styles/theme.js
  yarn.lock
Labels: ✨ Feature, 🎨 UI

#9 #8 [FEAT] 앨범 페이지 마크업 및 스타일링
  src/assets/icons/icon.svg
  src/components/Avatar/Avatar.jsx
  src/components/Avatar/Avatar.style.jsx
  src/components/Avatar/index.js
  src/components/Button/Button.style.jsx
  src/components/DropDown/DropDown.jsx
  src/components/DropDown/DropDown.style.jsx
  src/components/DropDown/index.js
  src/components/Header/Header.jsx
  src/components/Profile/Profile.jsx
  src/components/Profile/Profile.style.jsx
  src/components/RandomFriend/RandomFriend.jsx
  src/components/Search/Search.jsx
  src/components/Search/Search.style.jsx
  src/components/Search/index.js
  src/components/Sidebar/Sidebar.style.jsx
  src/constants/index.js
  src/constants/sort.js
  src/dummy/data/album.js
  src/dummy/data/index.js
  src/dummy/images/cat1.png
  src/dummy/images/cat2.png
  src/dummy/images/index.js
  src/index.css
  src/pages/AlbumPage/AlbumButton/AlbumButton.jsx
  src/pages/AlbumPage/AlbumButton/AlbumButton.style.jsx
  src/pages/AlbumPage/AlbumItem/AlbumItem.jsx
  src/pages/AlbumPage/AlbumItem/AlbumItem.style.jsx
  src/pages/AlbumPage/AlbumPage.jsx
  src/pages/AlbumPage/AlbumPage/AlbumPage.jsx
  src/pages/AlbumPage/AlbumPage/AlbumPage.style.jsx
  src/pages/AlbumPage/index.js
  src/styles/theme.js
Labels: ✨ Feature, 🎨 UI

#13 #11[FEAT] 앨범 제작 페이지 마크업 및 스타일링
  .github/ISSUE_TEMPLATE/bug-report.md
  .github/ISSUE_TEMPLATE/feature_request.md
  .github/ISSUE_TEMPLATE/refactor-template.md
  package.json
  src/assets/icons/icon.svg
  src/components/AlbumMaking/MainArea.jsx
  src/components/AlbumMaking/MainArea.style.jsx
  src/components/AlbumMaking/MakingModal.jsx
  src/components/AlbumMaking/MakingModal.style.jsx
  src/components/AlbumMaking/Side.jsx
  src/components/AlbumMaking/Side.style.jsx
  src/components/AlbumMaking/index.js
  src/constants/menu.js
  src/main.jsx
  src/pages/AlbumMakingPage/AlbumMakingPage.jsx
  src/pages/AlbumMakingPage/AlbumMakingPage.style.jsx
  src/pages/AlbumMakingPage/index.js
  src/store/store.js
  yarn.lock
Labels: ✨ Feature, 🎨 UI

#24 #23 [FEAT] 라우트에 따른 조건부 렌더링
  src/App.jsx
  src/main.jsx
  src/route.jsx
  src/utils/findRouteByPath.js
Labels: ✨ Feature

#28 #25 [FEAT] 사용자 프로필 페이지 UI
  src/assets/icons/icon.svg
  src/components/Button/Button.style.jsx
  src/components/Header/Header.jsx
  src/components/Input/Checkbox/Checkbox.jsx
  src/components/Input/Checkbox/Checkbox.style.jsx
  src/components/Input/Dropdown/Dropdown.jsx
  src/components/Input/Dropdown/Dropdown.style.jsx
  src/components/Input/Radio/Radio.jsx
  src/components/Input/Radio/Radio.style.jsx
  src/components/Input/RadioGroup/RadioGroup.jsx
  src/components/Input/RadioGroup/RadioGroup.style.jsx
  src/components/Input/TextInput/TextInput.jsx
  src/components/Input/TextInput/TextInput.style.jsx
  src/components/Input/index.js
  src/constants/index.js
  src/constants/option.js
  src/pages/AlbumMakingPage/index.js
  src/pages/UserProfilePage/UserProfilePage.jsx
  src/pages/UserProfilePage/UserProfilePage.style.jsx
  src/pages/UserProfilePage/index.js
  src/route.jsx
Labels: 🎨 UI

#20 #19 [FEAT] 앨범 탐색 페이지 제작
  package-lock.json
  src/dummy/data/album.js
  src/pages/ExplorePage/ExplorePage.jsx
  src/pages/ExplorePage/ExplorePage.style.jsx
  yarn.lock
Labels: 🎨 UI

#27 #26 [FEAT] 앨범 제작 페이지 UI 변경
  src/assets/icons/icon.svg
  src/components/AlbumMaking/MainArea.jsx
  src/components/AlbumMaking/MainArea.style.jsx
  src/components/AlbumMaking/MakingModal.jsx
  src/components/AlbumMaking/MakingModal.style.jsx
  src/components/Input/RadioGroup/RadioGroup.jsx
Labels: 🎨 UI

#31 #30 [FEAT] 설정 페이지 UI
  src/assets/icons/icon.svg
  src/components/Button/Button.style.jsx
  src/components/Header/Header.jsx
  src/pages/SettingPage/BlockListPage/BlockListPage.jsx
  src/pages/SettingPage/BlockListPage/BlockListPage.style.jsx
  src/pages/SettingPage/DeleteAccountPage/DeleteAccountPage.jsx
  src/pages/SettingPage/DeleteAccountPage/DeleteAccountPage.style.jsx
  src/pages/SettingPage/HelpPage/HelpPage.jsx
  src/pages/SettingPage/HelpPage/HelpPage.style.jsx
  src/pages/SettingPage/SettingPage.jsx
  src/pages/SettingPage/SettingPage.style.jsx
  src/pages/SettingPage/UpdateBlockListPage/Search.jsx
  src/pages/SettingPage/UpdateBlockListPage/Search.style.jsx
  src/pages/SettingPage/UpdateBlockListPage/UpdateBlockListPage.jsx
  src/pages/SettingPage/UpdateBlockListPage/UpdateBlockListPage.style.jsx
  src/pages/SettingPage/VisibilityPreferencePage/VisibilityPreferencePage.jsx
  src/pages/SettingPage/VisibilityPreferencePage/VisibilityPreferencePage.style.jsx
  src/pages/SettingPage/index.js
  src/route.jsx
Labels: 🎨 UI

#18 #7 [FEAT] 메인 페이지 마크업 및 스타일링
  package-lock.json
  package.json
  src/assets/icons/icon.svg
  src/components/AdComponent/AdComponent.jsx
  src/components/AdComponent/AdComponent.style.jsx
  src/components/AdComponent/index.js
  src/components/AlbumUpdates/AlbumUpdates.jsx
  src/components/AlbumUpdates/AlbumUpdates.style.jsx
  src/components/AlbumUpdates/index.js
  src/components/Feed/CommentSection.jsx
  src/components/Feed/CommentSection.style.jsx
  src/components/Feed/Feed.jsx
  src/components/Feed/Feed.style.jsx
  src/components/Feed/FeedItem.jsx
  src/components/Feed/index.js
  src/components/RandomFriend/RandomFriend.style.jsx
  src/dummy/data/albumupdates.js
  src/dummy/data/comments.js
  src/dummy/data/index.js
  src/dummy/images/albumThumbnail.png
  src/dummy/images/index.js
  src/pages/MainPage/MainPage.jsx
  src/pages/MainPage/MainPage.style.jsx
  src/pages/MainPage/index.js
  yarn.lock
Labels: 🎨 UI

#40 #36 [FEAT] 앨범 리스트 조회 API 연결
  package.json
  src/apis/album.js
  src/axios/index.js
  src/constants/sort.js
  src/main.jsx
  src/pages/AlbumPage/AlbumItem/AlbumItem.jsx
  src/pages/AlbumPage/AlbumPage/AlbumPage.jsx
  yarn.lock
Labels: ↔️ API

#35 #29 [FEAT] 로그인 페이지 기능 구현
  package.json
  src/assets/icons/icon.svg
  src/components/LoginComponents/LoginHeader.jsx
  src/components/LoginComponents/TitleContainer.jsx
  src/components/LoginComponents/TitleContainer.style.jsx
  src/dummy/data/user.js
  src/pages/AddInfoPage/AddInfoPage.jsx
  src/pages/AddInfoPage/AddInfoPage.style.jsx
  src/pages/AgreePage/AgreePage.jsx
  src/pages/AgreePage/AgreePage.style.jsx
  src/pages/LoginPage/LoginPage.jsx
  src/pages/LoginPage/LoginPage.style.jsx
  src/pages/PwdChangePage/PwdChangePage.jsx
  src/pages/PwdChangePage/PwdChangePage.style.jsx
  src/pages/PwdSearchPage/PwdSearchPage.jsx
  src/pages/PwdSearchPage/PwdSearchPage.style.jsx
  src/pages/RegisteredPage/RegisteredPage.jsx
  src/pages/RegisteredPage/RegisteredPage.style.jsx
  src/pages/SetNicknamePage/SetNicknamePage.jsx
  src/pages/SetNicknamePage/SetNicknamePage.style.jsx
  src/pages/SignUpPage/SignUpPage.jsx
  src/pages/SignUpPage/SignUpPage.style.jsx
  yarn.lock
Labels: ✨ Feature

#44 #43 [FEAT] 앨범 상세 조회 API 연결
  src/apis/album.js
  src/components/AlbumInfo/AlbumInfo.jsx
  src/components/AlbumViewer/AlbumViewer.jsx
  src/hooks/useAuth.jsx
  src/main.jsx
  src/pages/AlbumDetailPage/AlbumDetailPage.jsx
  src/pages/AlbumPage/AlbumItem/AlbumItem.jsx
  src/pages/AlbumPage/AlbumPage/AlbumPage.jsx
  src/route.jsx
  src/utils/convertDate.js
  src/utils/formatNumber.js
Labels: ↔️ API

#45 #39 [STYLE] 앨범 상세 페이지에 수정, 삭제 버튼 추가
  src/components/AlbumViewer/AlbumViewer.style.jsx
  src/pages/AlbumDetailPage/AlbumDetailPage.jsx
  src/pages/AlbumDetailPage/AlbumDetailPage.style.jsx
Labels: 🎨 UI

#48 #41 [FEAT] 앨범 삭제 API 연결
  src/apis/album.js
  src/components/AlbumDetail/AlbumDetail.jsx
  src/components/Chatting/Chatting.jsx
  src/components/UserInfo/UserInfo.jsx
  src/hooks/useAuth.jsx
  src/pages/AlbumDetailPage/AlbumDetailPage.jsx
  src/route.jsx
Labels: ↔️ API

#51 #50 [FEAT] 친구 페이지 UI
  src/pages/FriendPage/FriendPage.jsx
  src/pages/FriendPage/FriendPage.style.jsx
Labels: 🎨 UI

#54 #52 [FEAT] 친구 목록 조회 API 연결
  src/apis/friend.js
  src/components/Avatar/Avatar.jsx
  src/components/RandomFriend/RandomFriend.jsx
  src/pages/FriendPage/FriendPage.jsx
Labels: ↔️ API

#56 #55 [CHORE] 서버 도메인 환경변수로 전환
  src/axios/index.js
Labels: ⚙️ Setting

#62 #61 [FIX] 배포 오류 수정
  netlify.toml
  src/components/Chatting/Chatting.jsx
Labels: 🔧 Fix

#63 #59 [ MERGE] 개발 브랜치를 배포 브랜치로 머지
  netlify.toml
  src/components/Chatting/Chatting.jsx
Labels: 🌏 Deploy

#64 #61 [FIX] 채팅 스타일 컴포넌트 경로 오타 수정
  src/components/Chatting/Chatting.jsx
Labels: 🔧 Fix, 🌏 Deploy

#65 #59 [MERGE] 배포 브랜치로 머지
  src/components/Chatting/Chatting.jsx
Labels: 🌏 Deploy

#66 #61 [FIX] 빌드 폴더명 정정
  netlify.toml
Labels: 🔧 Fix, 🌏 Deploy

#67 #59 [MERGE] 배포 브랜치로 머지
  netlify.toml
Labels: 🌏 Deploy

#72 #69 [FEAT] 친구 요청 관련 API 연결
  src/apis/friend.js
  src/components/RandomFriend/RandomFriend.jsx
  src/components/RandomFriend/RandomFriend.style.jsx
  src/components/Target/Target.jsx
  src/components/Target/index.js
  src/hooks/useIntersect.jsx
  src/hooks/usePagination.jsx
  src/pages/FriendPage/Common.Style.jsx
  src/pages/FriendPage/FriendList/FriendList.jsx
  src/pages/FriendPage/FriendPage.jsx
  src/pages/FriendPage/FriendPage.style.jsx
  src/pages/FriendPage/FriendReceivedList/FriendReceivedList.jsx
  src/pages/FriendPage/FriendSentList/FriendSentList.jsx
  src/pages/FriendPage/index.js
  src/route.jsx
Labels: ↔️ API

#74 #73 [FEAT] 친구 삭제 API 연결
  src/apis/friend.js
  src/pages/FriendPage/FriendList/FriendList.jsx
  src/pages/FriendPage/FriendReceivedList/FriendReceivedList.jsx
Labels: ↔️ API

#75 [MERGE] 배포 브랜치에 머지
  src/apis/addInfo.js
  src/apis/certificationCode.js
  src/apis/changePw.js
  src/apis/friend.js
  src/apis/login.js
  src/apis/nickname.js
  src/apis/signUp.js
  src/components/RandomFriend/RandomFriend.jsx
  src/components/RandomFriend/RandomFriend.style.jsx
  src/components/Sidebar/Sidebar.jsx
  src/components/Target/Target.jsx
  src/components/Target/index.js
  src/hooks/useIntersect.jsx
  src/hooks/usePagination.jsx
  src/pages/AddInfoPage/AddInfoPage.jsx
  src/pages/FriendPage/Common.Style.jsx
  src/pages/FriendPage/FriendList/FriendList.jsx
  src/pages/FriendPage/FriendPage.jsx
  src/pages/FriendPage/FriendPage.style.jsx
  src/pages/FriendPage/FriendReceivedList/FriendReceivedList.jsx
  src/pages/FriendPage/FriendSentList/FriendSentList.jsx
  src/pages/FriendPage/index.js
  src/pages/LoginPage/LoginPage.jsx
  src/pages/PwdChangePage/PwdChangePage.jsx
  src/pages/PwdSearchPage/PwdSearchPage.jsx
  src/pages/SetNicknamePage/SetNicknamePage.jsx
  src/pages/SetNicknamePage/SetNicknamePage.style.jsx
  src/pages/SignUpPage/SignUpPage.jsx
  src/route.jsx
Labels: 🌏 Deploy

#78 #73 [MODIFY] 친구 삭제 API 스펙 변경
  src/apis/friend.js
Labels: ↔️ API

#80 #70 [MODIFY] 앨범 리스트 조회(사용자) API 기능 변경 사항 수정
  src/apis/album.js
  src/hooks/useAuth.jsx
  src/hooks/useInfiniteScroll.jsx
  src/pages/AlbumPage/AlbumItem/AlbumItem.jsx
  src/pages/AlbumPage/AlbumPage/AlbumPage.jsx
  src/route.jsx
Labels: ✨ Feature

#83 #82 [FEAT] Profile 컴포넌트에 서버 데이터 연결
  src/apis/friend.js
  src/components/Profile/Profile.jsx
  src/components/Profile/Profile.style.jsx
  src/components/RandomFriend/RandomFriend.jsx
  src/hooks/useFriend.jsx
  src/pages/AlbumPage/AlbumPage/AlbumPage.jsx
  src/pages/FriendPage/FriendList/FriendList.jsx
  src/pages/FriendPage/FriendReceivedList/FriendReceivedList.jsx
  src/pages/FriendPage/FriendSentList/FriendSentList.jsx
Labels: ↔️ API

#85 #84 [FEAT] 홈 게시글 리스트 API 연결
  src/apis/album.js
  src/assets/icons/icon.svg
  src/components/Feed/Feed.jsx
  src/components/Feed/FeedItem.jsx
  src/dummy/images/index.js
  src/hooks/usePagination.jsx
  src/pages/MainPage/MainPage.jsx
  src/pages/MainPage/MainPage.style.jsx
Labels: ↔️ API

#89 [MERGE] 배포 브랜치로 머지
  package-lock.json
  src/apis/addInfo.js
  src/apis/album.js
  src/apis/deleteAccount.js
  src/apis/friend.js
  src/apis/nickname.js
  src/assets/icons/icon.svg
  src/axios/index.js
  src/components/AlbumDetail/AlbumDetail.jsx
  src/components/AlbumDetail/CommentSection.jsx
  src/components/Feed/CommentSection.jsx
  src/components/Feed/Feed.jsx
  src/components/Feed/FeedItem.jsx
  src/components/Profile/Profile.jsx
  src/components/Profile/Profile.style.jsx
  src/components/RandomFriend/RandomFriend.jsx
  src/dummy/images/index.js
  src/hooks/useAuth.jsx
  src/hooks/useFriend.jsx
  src/hooks/useInfiniteScroll.jsx
  src/hooks/usePagination.jsx
  src/pages/AddInfoPage/AddInfoPage.jsx
  src/pages/AlbumPage/AlbumItem/AlbumItem.jsx
  src/pages/AlbumPage/AlbumPage/AlbumPage.jsx
  src/pages/BookmarkPage/BookmarkPage.jsx
  src/pages/FriendPage/FriendList/FriendList.jsx
  src/pages/FriendPage/FriendReceivedList/FriendReceivedList.jsx
  src/pages/FriendPage/FriendSentList/FriendSentList.jsx
  src/pages/LoginPage/LoginPage.jsx
  src/pages/MainPage/MainPage.jsx
  src/pages/MainPage/MainPage.style.jsx
  src/pages/SetNicknamePage/SetNicknamePage.jsx
  src/pages/SettingPage/DeleteAccountPage/DeleteAccountPage.jsx
  src/pages/SettingPage/DeleteAccountPage/DeleteAccountPage.style.jsx
  src/route.jsx
  yarn.lock
Labels: 🌏 Deploy

#91 #90 [FEAT] axios 에러를 제일 상위에서 핸들링
  src/main.jsx
Labels: ✨ Feature

#92 #68 [FEAT] 앨범 수정 API 연결
  src/apis/album.js
  src/components/AlbumMaking/index.js
  src/components/Edit/Edit.jsx
  src/components/Edit/Edit.style.jsx
  src/components/Edit/index.js
  src/components/Profile/Profile.jsx
  src/components/Profile/Profile.style.jsx
  src/constants/index.js
  src/constants/scope.js
  src/hooks/useAuth.jsx
  src/pages/AlbumDetailPage/AlbumDetailPage.jsx
  src/pages/AlbumEditPage/AlbumEditPage.jsx
  src/pages/AlbumEditPage/AlbumEditPage.style.jsx
  src/pages/AlbumEditPage/index.js
  src/pages/AlbumPage/AlbumItem/AlbumItem.jsx
  src/pages/AlbumPage/AlbumPage/AlbumPage.jsx
  src/route.jsx
Labels: ↔️ API

#94 #93 [FEAT] 서버 404 응답 코드 핸들링
  src/main.jsx
Labels: ✨ Feature

#95 [MERGE] 배포 브랜치에 머지
  src/apis/album.js
  src/components/AlbumMaking/index.js
  src/components/Edit/Edit.jsx
  src/components/Edit/Edit.style.jsx
  src/components/Edit/index.js
  src/components/Profile/Profile.jsx
  src/components/Profile/Profile.style.jsx
  src/constants/index.js
  src/constants/scope.js
  src/hooks/useAuth.jsx
  src/main.jsx
  src/pages/AlbumDetailPage/AlbumDetailPage.jsx
  src/pages/AlbumEditPage/AlbumEditPage.jsx
  src/pages/AlbumEditPage/AlbumEditPage.style.jsx
  src/pages/AlbumEditPage/index.js
  src/pages/AlbumPage/AlbumItem/AlbumItem.jsx
  src/pages/AlbumPage/AlbumPage/AlbumPage.jsx
  src/route.jsx
Labels: 🌏 Deploy

#98 #96 [FEAT] 리액트 쿼리 refetch 전역 설정 변경
  src/main.jsx
Labels: ✨ Feature

#100 [FIX] 앨범 상세 userId -> nickname
  src/hooks/useAuth.jsx
  src/pages/AlbumDetailPage/AlbumDetailPage.jsx
  src/route.jsx
Labels: 🔧 Fix

#101 [FIX] useInfiniteScroll을 usePagination으로 교체
  src/pages/AlbumPage/AlbumPage/AlbumPage.jsx
Labels: 🔧 Fix
